name: Multi arch Docker image

on:
  push:
    tags:
      - '**'

# see https://github.com/docker/build-push-action#usage
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # The branch or tag name that triggered the workflow run.
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - run: echo ${{github.ref_name}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shin1x1/test-multi-arch:${{github.ref_name}}